### ISSUE TITLE
Night mode по расписанию

### ISSUE THREAD

**Issue by krikunts** [keyten/HES#13]
Есть мысль реализовать включение night mode стилей по расписанию в ночные часы. Есть несколько связанных с этим вопросов:
1. Нужно ли это кому-нибудь вообще?
2. Задание времени включения / выключения:
   - хардкод
   - настройки
   - на основе времени захода и восхода солнца в текущий день (?)
3. Нужно ли включение/выключение расписания для постоянного нахождения в night mode

**Comment by extempl** [comment]
Одно маленькое уточнение перекрывает все возможные плюшки от этого - время дня здесь ни при чём, нужно знать освещение в комнате.
Я думаю, что открыть настройки и жмакнуть кнопку чтоб включить/выключить тёмный стиль достаточно просто.

**Comment by keyten** [comment]
Согласен с @extempl, вряд ли это нужно.
