### ISSUE TITLE
Настройки

### ISSUE THREAD

**Issue by krikunts** [keyten/HES#14]
На маленьком мониторе настройки HES перекрывают кнопку выхода
![скрин](https://s13.postimg.org/e3uuiveev/HES-bug.png)

**Comment by extempl** [comment]
Я вижу два варианта решения:
1. [Сжимать внутренние отступы ссылок](http://content.screencast.com/users/extempl/folders/Jing/media/47006bf4-0c0d-4144-aa40-809a11106d14/00000179.png)
Минусы - в какой-то момент всё-равно будет мало места, ломает некоторые места в других вкладках (всё можно пофиксить)
2. [В два столбца](http://content.screencast.com/users/extempl/folders/Jing/media/848eda64-fe63-4b7f-8305-9a96714e2171/00000178.png)
Минусы - при пропорционально маленьком экране оно будет занимать пол-экрана. В какой-то момент тоже будет места не хватать, в принципе можно скомбинировать с первым.

**Comment by krikunts** [comment]
Мне нравится вариант с двумя столбцами. С ним легче визуально отделить два вида настроек. Занимаемое место в ширину по-моему не критично, так как их всегда можно свернуть обратно.

**Comment by extempl** [comment]
https://github.com/keyten/HES/pull/18

**Comment by keyten** [comment]
Ещё один вариант:
https://github.com/keyten/HES/commit/79a226e5b494069f96a1f66a42c734d887938245
по клику по заголовку меню исчезает.
