### ISSUE TITLE
Night Mode + MathJax

### ISSUE THREAD

**Issue by XakepSDK** [keyten/HES#21]
Если включить Night Mode и MathJax, то появляется горизонтальная полоса прокрутки.

**Comment by XakepSDK** [comment]
UPD: Проблема не в этом, но у меня получилось вообще сломать скрипт.

**Comment by XakepSDK** [comment]
Очистка localStorage всё починила.

**Comment by XakepSDK** [comment]
UPD: проблема с горизонтальным скроллбаром осталась, работает только в Night Mode, без разницы, включен ли MathJax. Работает только если немного проскроллить вниз.

**Comment by extempl** [comment]
@XakepSDK Пример страницы, скриншот?
ОС, браузер?

**Comment by XakepSDK** [comment]
Firefox 46.0.1 64 bit, windows 7.
http://puu.sh/p3x2Y/a22bd5ada9.jpg
http://puu.sh/p3x3S/7ac45c6ddd.jpg

В первом случае проскроллил чуть ниже.

**Comment by extempl** [comment]
Исправил: https://github.com/WaveCutz/habrahabr.ru_night-mode/commit/875a4ed413b1172d48fdda32755a431758ba43f2
