### ISSUE TITLE
Скрытие потоков не работает

### ISSUE THREAD

**Issue by XakepSDK** [keyten/HES#22]
Firefox 46.0.1, 64bit
marketing, management, design

**Comment by extempl** [comment]
Именно потоков? Скрытие там так же работает, как и хабов, то есть если включено частичное скрытие, они не будут скрыты полностью. У меня в ФФ работает. Можно пример со скрином, где хаб, например, работает, а поток нет?

**Comment by XakepSDK** [comment]
Я не знаю, почему, но иногда всё же посты проскакивают. Сейчас например всё работает, а утром и вчера еще было пара постов из маркетинга.

**Comment by extempl** [comment]
Исправил: https://github.com/keyten/HES/commit/7a3a71c45ebd03c06e419968ddc493139772fb20
Скрытие могло запуститься раньше, чем загрузится документ, потому иногда скрывалось, иногда нет.
