### ISSUE TITLE
Несовместимо с новым дизайном

### ISSUE THREAD

**Issue by doz10us** [keyten/HES#24]
В [новом дизайне](https://habrahabr.ru/company/tm/blog/310592/) скрипт не работает практически никак. Почините, пожалуйста.

**Comment by extempl** [comment]
Справедливости ради, не работает только меню, всё остальное работает. Мы подумаем куда его (меню) прицепить и обновим.

**Comment by doz10us** [comment]
@extempl Прошу прощения, действительно работает. Вчера форматирование сильно билось, отключил скрипт почти сразу. Либо на сайте что-то подправили, либо у меня кеш продумался наконец.

**Comment by extempl** [comment]
e4e3eed80484b5e0517dcd7b378a6b6c3eb25e9d
