### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by nesteruk** [keyten/HES#26]
Просто ничего не работает. Поставил на хром под tampermonkey, захожу на Хабр, на tampermonkey загорается единичка (1), скрипт точно включен, но ничего не делает, Хабр выглядит ровно так же.

**Comment by nesteruk** [comment]
Ан нет. Оказалось что даже когда подключается скрипт и загорается единичка, скрипт-то не включен. Неплохо было бы объяснить юзерам как его включать.

**Comment by extempl** [comment]
Обновил скриншот. 
В принципе зная где находится панель и по самому списку возможностей вроде всё более-менее понятно. Или нужна именно инструкция "требует изначальной настройки"?

**Comment by nesteruk** [comment]
Да просто нужна заметка что «включите вот тут чтобы заработало».
