### ISSUE TITLE
Не выпадает главное меню

### ISSUE THREAD

**Issue by krikunts** [keyten/HES#29]
Начиная с перехода на новый дизайн не открывается меню HES в Firefox-е. 
По клику на кнопку HES ничего не происходит, ошибок в JS консоли нет.
Проверено сегодня на версии Firefox 50.1.0 под Win.
В Chrome меню работает нормально.

**Comment by extempl** [comment]
@krikunts проверил у себя на той же версии FF, но на маке - всё работает. 
Открывается ли меню под иконкой пользователя?
Работает ли при этом сам скрипт?

**Comment by krikunts** [comment]
Только что поняла, что это похоже адблок как-то заблокировал выпадание меню, так что вопрос снимается.

**Comment by krikunts** [comment]
Если у кого-то еще будет такое же, то проблема была в этом фильтре:
||habrahabr.ru/hauusbx/al/habrahabr/

который входит в подписку RuAdList + EasyList
