### ISSUE TITLE
Активные ссылки

### ISSUE THREAD

**Issue by extempl** [keyten/HES#6]
Возникла мысль, что неплохо было бы искать на странице текст-ссылку и делать его активной ссылкой, возможно с варнингом - выделять красным. 
Поскольку это наказание не только для тех, кто постит (невозможность пользоваться html при низкой карме), но и для тех, кто читает. Всё-равно ведь приходится выделять и копипастить - кому от этого легче?

**Comment by keyten** [comment]
Я за.
Сюда же можно картинки (ссылки, оканчивающиеся на на jpg / gif / png).

**Comment by extempl** [comment]
https://github.com/keyten/HES/pull/8
Картинки стрёмно, там может быть и килограмовая картинка и такая, которую не стоит вставлять :) Не говоря уже о какой-нибудь исполняемой дряни. 
Хотя такие штуки как видео ссылки можно было бы добавлять в спойлер.

В любом случае, в этом пулреквесте такие ссылки (на картинки и видео) будут ставать кликабельными ссылками с переходом в новую вкладку, что тоже ок.

**Comment by keyten** [comment]
Ага.
Спасибо :)
